create book entity, dao, service
Parashchuk/online-book-store pull request #1
Opened 2023-10-18 07:28 UTC by Parashchuk

2023-10-18 13:11 UTC, liliia-ponomarenko requested changes
Good job! Let’s  fix a few mistakes ;)

2023-10-18 13:11 UTC, liliia-ponomarenko commented on src/main/java/bookstore/OnlineBookStoreApplication.java
> +            bookService.findAll();
you should add some data before findAll

2023-10-18 13:11 UTC, liliia-ponomarenko commented on src/main/java/bookstore/entity/Book.java
> +@Entity
Let’s  add Table annotation

2023-10-18 13:11 UTC, liliia-ponomarenko commented on src/main/java/bookstore/entity/Book.java
> +    private String coverImage;
```suggestion
    private BigDecimal price;
    private String description;
    private String coverImage;
```

2023-10-18 13:11 UTC, liliia-ponomarenko commented on src/main/java/bookstore/entity/Book.java
> +    }
You can add Lombok and use annotations Getter, Setter, ToString etc.

2023-10-18 13:11 UTC, liliia-ponomarenko commented on src/main/java/bookstore/repository/BookRepositoryImpl.java
> +    @Autowired
```suggestion
```
this annotation redundant from spring V4

2023-10-18 13:11 UTC, liliia-ponomarenko commented on src/main/java/bookstore/repository/BookRepositoryImpl.java
> +    }
use try-catch  construction (apply to all methods

2023-10-18 13:11 UTC, liliia-ponomarenko commented on src/main/java/bookstore/service/BookServiceImpl.java
> +    @Autowired
the same

2023-10-23 06:16 UTC, Elena-Bruyako requested changes
Well done! Let's improve your solution!

2023-10-23 06:16 UTC, Elena-Bruyako commented on src/main/java/bookstore/repository/BookRepositoryImpl.java
> +
remove empty line

2023-10-23 06:16 UTC, Elena-Bruyako commented on src/main/java/bookstore/repository/BookRepositoryImpl.java
> +            throw new RuntimeException("Save operation was unsuccessful: ", e);
It's bad practice to throw RuntimeException. Let's create custom DataProcessingException

Don't just copy-paste the message. 

"Can't find books" or "Can't get books from DB" will be better

2023-10-23 06:16 UTC, Elena-Bruyako commented on src/main/java/bookstore/repository/BookRepositoryImpl.java
> +            throw new RuntimeException("Save operation was unsuccessful: ", e);
It's bad practice to throw RuntimeException. Let's create custom DataProcessingException
The message could be "Can't save book to DB"

2023-10-23 06:16 UTC, Elena-Bruyako commented on src/main/java/bookstore/repository/BookRepositoryImpl.java
> +        try {
It's better to use try with resources here

2023-10-23 07:23 UTC, Elena-Bruyako approved these changes
Good job! Please fix one comment!

2023-10-23 07:23 UTC, Elena-Bruyako commented on src/main/java/bookstore/repository/BookRepositoryImpl.java
> +        try {
Not fixed

2023-10-24 07:08 UTC, merged