Implement category model
Parashchuk/online-book-store pull request #8
Opened 2023-11-13 16:15 UTC by Parashchuk

2023-11-14 07:59 UTC, pavlov-n approved these changes
Looks good

2023-11-14 14:21 UTC, liliia-ponomarenko requested changes
Good job! Let’s  improve  your solution ;)

2023-11-14 14:21 UTC, liliia-ponomarenko commented on src/main/java/bookstore/entity/category/Category.java
> +    private String description;
```suggestion
     private String description;
     
    @Column(nullable = false)
    private boolean isDeleted;
```

2023-11-14 14:21 UTC, liliia-ponomarenko commented on src/main/java/bookstore/mapper/BookMapper.java
>      Book toModel(BookRequestDto bookRequestDto);
Modify the BookMapper class to have such methods:
BookDto toDto(Book book);
Book toEntity(CreateBookRequestDto bookDto);
BookDtoWithoutCategoryIds toDtoWithoutCategories(Book book); (HINT: BookDtoWithoutCategoryIds class could be used as a response class for @GetMapping("/{id}/books") endpoint)
@AfterMapping default void setCategoryIds(@MappingTarget BookDto bookDto, Book book)

2023-11-14 14:21 UTC, liliia-ponomarenko commented on src/main/java/bookstore/service/BookService.java
>      BookResponseDto save(BookRequestDto book);
use BookDtoWithoutCategoryIds (check other methods)

2023-11-14 14:21 UTC, liliia-ponomarenko commented on src/main/java/bookstore/service/impl/BookServiceImpl.java
> +        return bookMapper.toDto(bookRepository.save(bookMapper.toModel(bookRequestDto)));
Can you save the book with categories? Let’s  fix it ;)

2023-11-14 14:21 UTC, liliia-ponomarenko commented on src/main/java/bookstore/service/impl/CategoryServiceImpl.java
> +        );
you can use existById

2023-11-14 14:35 UTC, liliia-ponomarenko commented on src/main/java/bookstore/service/BookService.java
> +    List<BookResponseDto> findAllByCategoryId(Long id, Pageable pageable);
Can you use BookDtoWithoutCategoryIds? (check other methods)

2023-11-29 10:13 UTC, liliia-ponomarenko approved these changes
Good job! But fix my comments before merging  ;)

2023-11-29 10:13 UTC, liliia-ponomarenko commented on src/main/java/bookstore/controller/BookController.java
> -            @Valid @RequestBody BookRequestDto book
UpdateBookRequestDto

2023-11-29 10:13 UTC, liliia-ponomarenko commented on src/main/java/bookstore/controller/BookController.java
> +    public BookResponseDto createBook(@RequestBody @Valid BookCreateDto book) {
CreateBookCreateDto

2023-11-29 10:13 UTC, liliia-ponomarenko commented on src/main/java/bookstore/mapper/BookMapper.java
> +
leave only one empty line

2023-11-29 10:13 UTC, liliia-ponomarenko commented on src/main/java/bookstore/repository/BookRepository.java
> +    List<Book> findByIdNotNull(Pageable pageable);
Can ID be null?

2023-11-29 14:02 UTC, merged