Shopping cart
Parashchuk/online-book-store pull request #9
Opened 2023-11-26 13:41 UTC by Parashchuk

2023-11-27 15:21 UTC, Elena-Bruyako requested changes
Your PR should not include changes from your previous HW - category.

2023-11-29 15:53 UTC, Elena-Bruyako requested changes
Good job! Let's fix some comments

2023-11-29 15:53 UTC, Elena-Bruyako commented on src/main/java/bookstore/dto/cart/CartRequestAddDto.java
> +        @Min(value = 1)
Why not ` @Positive `?

2023-11-29 15:53 UTC, Elena-Bruyako commented on src/main/java/bookstore/dto/cart/CartRequestUpdateDto.java
> +        @Min(value = 1)
the same

2023-11-29 15:53 UTC, Elena-Bruyako commented on src/main/java/bookstore/entity/cart/Cart.java
> +    @JoinColumn(name = "user_id")
nullable = false

2023-11-29 15:53 UTC, Elena-Bruyako commented on src/main/java/bookstore/entity/cart/CartItem.java
> +    @ManyToOne
```suggestion
    @ManyToOne(fetch = FetchType.LAZY, optional = false)
```

2023-11-29 15:53 UTC, Elena-Bruyako commented on src/main/java/bookstore/entity/cart/CartItem.java
> +    @JoinColumn(name = "cart_id")
nullable = false

2023-11-29 15:53 UTC, Elena-Bruyako commented on src/main/java/bookstore/entity/cart/CartItem.java
> +    @OneToOne
Wrong mapping 
@ManyToOne(fetch = FetchType.LAZY, optional = false)

Also, check Book entity and add cartItems

2023-12-01 13:12 UTC, liliia-ponomarenko approved these changes
Good job!

2023-12-01 14:43 UTC, merged